version: '3'
    
services:  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - $PWD/code:/code
    ports:
      - "8000:8000"
    environment:
      DJANGO_ALLOWED_HOSTS: 'local.f6vings.ar localhost 127.0.0.1'