# Generated by Django 2.2.28 on 2023-08-09 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.PositiveIntegerField(choices=[(1, 'Draft'), (2, 'Sent'), (3, 'Approved'), (4, 'Rejected'), (5, 'In Progress'), (6, 'Finished'), (7, 'Delivered')], default=1)),
                ('deadline', models.DateField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
    ]
